[package]
name = "cloud-config-validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.1"
hyper = { version = "0.14.23", features = ["full"] }
jsonschema = "0.16.1"
reqwest = { version = "0.11.13", features = ["rustls-tls"] }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
tokio = { version = "1.23.0", features = ["full"] }
tower = "0.4.13"
